This is just one forward and backward pass of neural network
I/P : x (training input)
    : y (training output values)
    
O/P : trained and optimized values of the parameters

In [1]:
# Importing important library
import numpy as np
import random
# Training I/P given by variable : x
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print (x)
print (x.shape)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
(3, 4)


In [15]:
# Randomly initalised Weights for forward pass
def randomWeights(nrows,ncols):
    array=[]
    for i in range(nrows):
        alist=[]
        for j in range(ncols):
            alist.append(round(random.random(),2))
        array.append(alist)
    return np.array(array)
       
wh=randomWeights(4,3)
print (wh)
print (wh.shape)
    

[[ 0.34  0.21  0.61]
 [ 0.05  0.99  0.9 ]
 [ 0.06  0.45  0.38]
 [ 0.8   0.76  0.91]]
(4, 3)


In [16]:
#Randomly Initalised biases
def randomBiases(n):
    alist=[]
    for i in range(n):
        alist.append(round(random.random(),2))
    return np.array(alist)

bh=randomBiases(3)
print (bh)

[ 0.74  0.14  0.92]


1. calculate variable hidden_layer_input, which is given by the following    formula 

hidden_layer_input = matrixMultiplcation(x,wh)+bh

In [17]:
#calculating hidden_layer_input
hidden_layer_input=np.dot(x,wh)+bh
print (hidden_layer_input)

[[ 1.14  0.8   1.91]
 [ 1.94  1.56  2.82]
 [ 1.59  1.89  2.73]]


2. calculate variable hidden_layer_activation, which is nothing but          sigmoid of all the of all the values in hidden_layer_input

In [18]:
hidden_layer_input=np.dot(x,wh)+bh
def sigmoid(array):
    activation=np.exp(array)/(1+np.exp(array))
    return np.around(activation,2)
hidden_layer_activations=sigmoid(hidden_layer_input)
print (hidden_layer_activations)

[[ 0.76  0.69  0.87]
 [ 0.87  0.83  0.94]
 [ 0.83  0.87  0.94]]


3. Randomly intialise wout and bout
4. calculate the output of second layer

In [22]:
#Randomly initialise wout and bout
def randomWeights(n):
    alist=[]
    for i in range(n):
        alist.append(round(random.random(),2))
    return np.array(alist)
wout=randomWeights(3)
bout=round(random.random(),2)
print (wout)
print (bout)
#output is the 3rd layer in ANN
output=sigmoid(np.dot(hidden_layer_activations,wout)+bout)
print (output)


[ 0.56  0.17  0.68]
0.8
[ 0.87  0.89  0.89]


5. calculate the error (This is the final step of forward propogation)

In [23]:
y=np.array([1,1,0])
error=np.subtract(y,output)
print (error)


[ 0.13  0.11 -0.89]


##### Backpropogation starts 
1. calculate the derivative which for sigmoid function is a(1-a)
   - slope_ouput_layer
   - slope_hidden_layer

In [25]:
#function that calculated the dervative of sigmoid function
def derivativeS(arr):
    return np.around(arr*(1-arr),2)
slope_output_layer=derivativeS(output)
slope_hidden_layer=derivativeS(hidden_layer_activations)
print (slope_hidden_layer)
print (slope_output_layer)

[[ 0.18  0.21  0.11]
 [ 0.11  0.14  0.06]
 [ 0.14  0.11  0.06]]
[ 0.11  0.1   0.1 ]


2. calculating delta_output 
   - error*activation of 3rd layer

In [26]:
delta_output=np.around(error*slope_output_layer,2)
print (delta_output)


[ 0.01  0.01 -0.09]


3. Calculate Error at hidden layer

In [27]:

delta_output=np.reshape(delta_output,(3,1))
wout=np.reshape(wout,(3,1))
error_at_hidden_layer=np.dot(delta_output,wout.T)
print (error_at_hidden_layer)


[[ 0.0056  0.0017  0.0068]
 [ 0.0056  0.0017  0.0068]
 [-0.0504 -0.0153 -0.0612]]


4. Compute delta at hidden layer

In [28]:
delta_hiddenlayer=np.matmul(error_at_hidden_layer,slope_hidden_layer)
print (delta_hiddenlayer)


[[ 0.002147  0.002162  0.001126]
 [ 0.002147  0.002162  0.001126]
 [-0.019323 -0.019458 -0.010134]]


5. Update weight at both output and hidden layer

In [29]:
learning_rate=0.1
wout+=np.dot(hidden_layer_activations,delta_output)*learning_rate
wh+=np.dot(x.T,delta_hiddenlayer)*learning_rate
print (np.around(wout,2))
print (np.around(wh,2))

[[ 0.55]
 [ 0.16]
 [ 0.67]]
[[ 0.34  0.21  0.61]
 [ 0.05  0.99  0.9 ]
 [ 0.06  0.45  0.38]
 [ 0.8   0.76  0.91]]


6. Update biases at both output and hidden layer

In [32]:
bh+=np.sum(delta_hiddenlayer,axis=0)*learning_rate
print (np.round(bh,2))

[ 0.74  0.14  0.92]


In [33]:

bout+=np.sum(delta_output,axis=0)*learning_rate
print(np.around(bout,2))

[ 0.79]
